#!/bin/sh
set -x
switch=br0
if [ -n "$1" ]; then
    if ! ip link show "$1" >/dev/null 2>&1; then
        ip tuntap add "$1" mode tap user "$(whoami)"
    fi
    ip link set "$1" up
    sleep 0.5s
    sysctl -w net.ipv4.ip_forward=1
    ip route replace 192.168.1.10/32 dev "$1"
    exit 0
else
    echo "Error: no interface specified"
    exit 1
fi
